

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DAL.DataBase
{
    public partial class NewsPortalEntities : DbContext
{
    public NewsPortalEntities()
        : base("name=NewsPortalEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Catagory> Catagories { get; set; }

    public virtual DbSet<News> News { get; set; }

}

}

